# TuneConfig will set metric and mode on the search alg and the scheduler
tune_config:
  metric: kfold_val_accuracy_mean
  mode: max
  num_samples: 100
  search_alg:
    class_path: ray.tune.search.hyperopt.HyperOptSearch
    init_args:
      # Same as in pytorch, for reproducibility, the reset (like metric) will be set from TuneConfig
      random_state_seed: 127
#head_address: 10.10.10.53:6379
resources_per_trial:
  cpu: 16
  gpu: 1
  memory: 8.5e+10
hparams:
  model.init_args.optimizer_init.init_args.weight_decay: ray.tune.qloguniform(0.000001, 0.99, 0.00001)
  model.init_args.optimizer_init.init_args.lr: ray.tune.qloguniform(0.1, 2.0, 0.00001)
callback:
  class_path: callbacks.RunIDTuneRportCallback
  init_args:
    'metrics': kfold_val_accuracy_mean
    # NOTE, if you want to change the 'on', you need to change it also in the cli.py
    'on': test_end
scheduler:
  class_path: ray.tune.schedulers.ASHAScheduler
  init_args:
    'max_t': 3
    'grace_period': 1
    'reduction_factor': 2
